package com.wes.sleekfashion.navigation

const val ROUTE_HOME = "Home"
const val ROUTE_REGISTER ="Register"
const val ROUTE_LOGIN = "login"
const val ROUTE_MAIN_PRODUCTS_SCREEN = "products"
const val ROUTE_ADD_TO_CART = "CART"
const val ROUTE_MEN ="Men"
const val ROUTE_LADIES = "ladies"
const val ROUTE_KIDS ="kids"
const val ROUTE_HOODIE  = "H"
const val ROUTE_JEANS  = "J"
const val ROUTE_SHIRTS  = "S"
const val ROUTE_SHOES = "T"
const val ROUTE_SUITS  = "W"
const val ROUTE_TRACKS  = "Q"
const val ROUTE_BAG  = "R"
const val ROUTE_DRESS  = "Y"
const val ROUTE_GHOODIE  = "U"
const val ROUTE_HEELS  = "I"
const val ROUTE_PANTS  = "O"
const val ROUTE_TOPS  = "P"
const val ROUTE_JERSEY  = "A"
const val ROUTE_KIDSSHIRT  = "Y"
const val ROUTE_PAJAMAS  = "M"
const val ROUTE_SWEATERS  = "N"